#!/usr/bin/env python3

"""
STEP 6 — BUILD MEMORY-SAFE TRAINING PAIRS

Uses train_ground_truth.tsv directly.

Creates:
    output/training_pairs.tsv

Strategy:
    - stream the ground truth
    - keep positive S1 -> S2/S3 pairs
    - sample a controlled number of negatives
    - never load the complete ground truth into RAM

The negative examples are generated by pairing an S1 with
another record from the same source/country using deterministic
sampling. They are NOT assumed to be true matches.

No external data is used.
"""

from pathlib import Path
import csv
import random
import sqlite3
import time
import sys


BASE_DIR = Path(__file__).resolve().parent.parent

GROUND_TRUTH = (
    BASE_DIR
    / "dataset"
    / "train"
    / "train_ground_truth.tsv"
)

DB_PATH = (
    BASE_DIR
    / "output"
    / "entity_indexes.sqlite"
)

OUTPUT_DIR = BASE_DIR / "output"

OUTPUT_PATH = (
    OUTPUT_DIR
    / "training_pairs.tsv"
)

# ------------------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------------------

# Maximum positive examples.
# The complete GT contains ~7.64M positives.
# This keeps training manageable.
MAX_POSITIVES = 1_500_000

# Number of negatives.
MAX_NEGATIVES = 1_500_000

# Read GT in chunks.
GT_PROGRESS = 100_000

# Deterministic randomness.
RANDOM_SEED = 42

# Negative generation:
# select a different entity from the same country/source.
NEGATIVE_ATTEMPTS = 8


def check_files():

    if not GROUND_TRUTH.exists():
        print("ERROR: ground truth not found:")
        print(GROUND_TRUTH)
        sys.exit(1)

    if not DB_PATH.exists():
        print("ERROR: SQLite database not found:")
        print(DB_PATH)
        sys.exit(1)


def open_db():

    conn = sqlite3.connect(str(DB_PATH))

    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    conn.execute("PRAGMA temp_store=FILE")
    conn.execute("PRAGMA cache_size=-12000")

    return conn


def load_s1_metadata(conn):

    """
    Load only S1 metadata.

    This is ~2.2M rows and is too large for a normal Python dict
    on the user's machine.

    Instead, we keep the metadata inside SQLite and query it
    when needed.
    """

    return


def get_source_for_id(entity_id):

    if entity_id.startswith("S2-"):
        return "S2"

    if entity_id.startswith("S3-"):
        return "S3"

    return None


def build_positive_pairs():

    """
    Stream ground truth and create sampled positives.

    Sampling is deterministic.

    We use a hash-like deterministic decision rather than
    random.choice over a giant in-memory collection.
    """

    print()
    print("=" * 80)
    print("BUILDING POSITIVE TRAINING PAIRS")
    print("=" * 80)

    print()
    print("Ground truth:")
    print(GROUND_TRUTH)

    print()
    print(f"Maximum positives: {MAX_POSITIVES:,}")

    positives = []

    total_gt_rows = 0
    total_true_pairs = 0

    start = time.time()

    with GROUND_TRUTH.open(
        "r",
        encoding="utf-8",
        newline="",
    ) as f:

        reader = csv.DictReader(
            f,
            delimiter="\t",
        )

        for row in reader:

            total_gt_rows += 1

            s1_id = row["source1_entity_id"]
            matched = row["matched_entity_ids"]

            if not matched:
                continue

            ids = [
                x.strip()
                for x in matched.split(",")
                if x.strip()
            ]

            total_true_pairs += len(ids)

            # --------------------------------------------------
            # Deterministic sampling.
            #
            # Keep all pairs while below the target.
            # After that, use a deterministic hash threshold.
            # --------------------------------------------------

            for matched_id in ids:

                if len(positives) < MAX_POSITIVES:

                    positives.append(
                        (
                            s1_id,
                            matched_id,
                            1,
                        )
                    )

                else:

                    key = (
                        f"{s1_id}|{matched_id}|"
                        f"{RANDOM_SEED}"
                    )

                    value = hash(key) % 100

                    # Roughly 5% additional probability,
                    # but stop once the cap is reached.
                    if value < 5:
                        positives.append(
                            (
                                s1_id,
                                matched_id,
                                1,
                            )
                        )

                        if len(positives) >= MAX_POSITIVES:
                            break

            if total_gt_rows % GT_PROGRESS == 0:

                elapsed = time.time() - start

                print(
                    f"  GT rows: {total_gt_rows:>10,} "
                    f"| true pairs seen: {total_true_pairs:>12,} "
                    f"| positives kept: {len(positives):>10,} "
                    f"| {elapsed / 60:.2f} min",
                    flush=True,
                )

            # Once the cap is reached, we can stop reading.
            # The first section of the GT is already representative
            # enough for a baseline model, and this avoids unnecessary
            # processing on the 3.6 GB RAM machine.
            if len(positives) >= MAX_POSITIVES:
                break

    print()
    print(f"GT rows processed:       {total_gt_rows:,}")
    print(f"True pairs encountered:  {total_true_pairs:,}")
    print(f"Positive pairs kept:     {len(positives):,}")

    return positives


def create_negative_pairs(conn, positive_pairs):

    """
    Generate negatives from S1 records and S2/S3 records.

    The negative candidates are sampled by selecting records
    from the same country but a different entity.

    We explicitly avoid known positive pairs.

    A temporary SQLite table is used instead of a giant Python set.
    """

    print()
    print("=" * 80)
    print("BUILDING NEGATIVE TRAINING PAIRS")
    print("=" * 80)

    print()
    print(f"Target negatives: {MAX_NEGATIVES:,}")

    # --------------------------------------------------------------
    # Store positives in SQLite so negative generation can test
    # whether a pair is known positive.
    # --------------------------------------------------------------

    print()
    print("Creating temporary positive-pair table...")

    conn.execute(
        """
        DROP TABLE IF EXISTS temp.positive_pairs
        """
    )

    conn.execute(
        """
        CREATE TEMP TABLE positive_pairs (
            s1_id TEXT NOT NULL,
            matched_id TEXT NOT NULL,
            PRIMARY KEY (s1_id, matched_id)
        )
        """
    )

    batch = []

    for s1_id, matched_id, label in positive_pairs:

        batch.append(
            (
                s1_id,
                matched_id,
            )
        )

        if len(batch) >= 50_000:

            conn.executemany(
                """
                INSERT OR IGNORE INTO positive_pairs
                VALUES (?, ?)
                """,
                batch,
            )

            batch.clear()

    if batch:

        conn.executemany(
            """
            INSERT OR IGNORE INTO positive_pairs
            VALUES (?, ?)
            """,
            batch,
        )

    conn.commit()

    conn.execute(
        """
        CREATE INDEX temp.idx_positive_pairs
        ON positive_pairs(s1_id, matched_id)
        """
    )

    conn.commit()

    # --------------------------------------------------------------
    # Select S1 records using SQLite.
    # --------------------------------------------------------------

    print("Generating negatives...")

    random.seed(RANDOM_SEED)

    negatives = []

    # We sample S1 rows through SQLite.
    cursor = conn.execute(
        """
        SELECT entity_id, country
        FROM records
        WHERE source = 'S1'
        ORDER BY rowid
        """
    )

    processed_s1 = 0
    start = time.time()

    for s1_id, country in cursor:

        processed_s1 += 1

        if len(negatives) >= MAX_NEGATIVES:
            break

        # ----------------------------------------------------------
        # Alternate S2/S3 so both source types are represented.
        # ----------------------------------------------------------

        source = "S2" if processed_s1 % 2 == 0 else "S3"

        for _ in range(NEGATIVE_ATTEMPTS):

            # Random entity_id from the same country/source.
            row = conn.execute(
                """
                SELECT entity_id
                FROM records
                WHERE source = ?
                  AND country = ?
                ORDER BY RANDOM()
                LIMIT 1
                """,
                (
                    source,
                    country,
                ),
            ).fetchone()

            if not row:
                continue

            matched_id = row[0]

            # Never use the same ID.
            if matched_id == s1_id:
                continue

            # Never use a known positive.
            positive = conn.execute(
                """
                SELECT 1
                FROM positive_pairs
                WHERE s1_id = ?
                  AND matched_id = ?
                LIMIT 1
                """,
                (
                    s1_id,
                    matched_id,
                ),
            ).fetchone()

            if positive:
                continue

            negatives.append(
                (
                    s1_id,
                    matched_id,
                    0,
                )
            )

            break

        if processed_s1 % 50_000 == 0:

            elapsed = time.time() - start

            print(
                f"  S1 scanned: {processed_s1:>10,} "
                f"| negatives: {len(negatives):>10,} "
                f"| {elapsed / 60:.2f} min",
                flush=True,
            )

    print()
    print(f"S1 records scanned:     {processed_s1:,}")
    print(f"Negative pairs kept:    {len(negatives):,}")

    return negatives


def write_training_file(positives, negatives):

    print()
    print("=" * 80)
    print("WRITING TRAINING PAIRS")
    print("=" * 80)

    if OUTPUT_PATH.exists():
        OUTPUT_PATH.unlink()

    total = 0

    with OUTPUT_PATH.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as f:

        writer = csv.writer(
            f,
            delimiter="\t",
            lineterminator="\n",
        )

        writer.writerow(
            [
                "s1_entity_id",
                "matched_entity_id",
                "matched_source",
                "label",
            ]
        )

        for s1_id, matched_id, label in positives:

            writer.writerow(
                [
                    s1_id,
                    matched_id,
                    get_source_for_id(matched_id),
                    label,
                ]
            )

            total += 1

        for s1_id, matched_id, label in negatives:

            writer.writerow(
                [
                    s1_id,
                    matched_id,
                    get_source_for_id(matched_id),
                    label,
                ]
            )

            total += 1

    print()
    print("Training file:")
    print(OUTPUT_PATH)

    print()
    print(f"Total training pairs: {total:,}")
    print(f"Positive pairs:       {len(positives):,}")
    print(f"Negative pairs:       {len(negatives):,}")


def main():

    print("=" * 80)
    print("BUSINESS ENTITY RESOLUTION")
    print("STEP 6 — BUILD TRAINING PAIRS")
    print("=" * 80)

    check_files()

    start = time.time()

    conn = open_db()

    try:

        positives = build_positive_pairs()

        if not positives:
            print()
            print("ERROR: no positive pairs were created.")
            sys.exit(1)

        negatives = create_negative_pairs(
            conn,
            positives,
        )

    finally:

        conn.close()

    write_training_file(
        positives,
        negatives,
    )

    elapsed = time.time() - start

    print()
    print("=" * 80)
    print("STEP 6 COMPLETE")
    print("=" * 80)

    print()
    print(
        f"Total runtime: {elapsed / 60:.2f} minutes"
    )

    print()
    print("Next:")
    print("  STEP 7 — Extract pair features")
    print("  STEP 8 — Train and validate matcher")


if __name__ == "__main__":
    main()
